baseURL = 'https://52454d434f.github.io/morce.codes-HUGO/'
languageCode = 'en-us'
title = 'M -- O --- R .-. C -.-. E . codes'
theme = 'nojs'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 2

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 3
